### ISSUE TITLE
オブジェクト指向分析

### ISSUE THREAD

**Issue by trapedev** [1934372T/VYD#16]

**Comment by trapedev** [comment]
![ファイルアップロード drawio](https://github.com/1934372T/VYD/assets/67819217/6d57c85b-daf2-4f41-a5fe-bf6b792b0997)

**Comment by tkt-ino** [comment]
![domain drawio](https://github.com/1934372T/VYD/assets/100588602/8a2fbe36-dc8f-4e88-8ac4-f033544a9031)

**Comment by tkt-ino** [comment]
![ロバストネス図 drawio](https://github.com/1934372T/VYD/assets/100588602/2a345250-5e6f-4566-b595-11bf51da2af2)

**Comment by tkt-ino** [comment]
![ロバストネス図2 drawio](https://github.com/1934372T/VYD/assets/100588602/a6c1368a-941c-4b06-aad7-f4c61a7706f4)

**Comment by tkt-ino** [comment]
![シーケンス図 drawio](https://github.com/1934372T/VYD/assets/100588602/d1c8e7ab-9274-47fa-ba5b-fa5f686812d0)

**Comment by tkt-ino** [comment]
![ロバストネス図 drawio](https://github.com/1934372T/VYD/assets/100588602/052d0d49-67fa-42e6-af13-6f79489d56ec)

**Comment by tkt-ino** [comment]
![template-ページ4 drawio](https://github.com/1934372T/VYD/assets/100588602/e57b559b-d05b-4f26-b3e4-ff8b6b53df15)
